# Site settings
title: Yang Kuang
email: ykuang@gdut.edu.cn
description: Personal webpage of Dr. Yang Kuang
baseurl: ""
url: ""
affiliation: <a href="https://math.gdut.edu.cn/" target="_blank">School of Mathematics and Statistics</a> at Guangdong Univerisity of Technology.

# Google analytics ID
google_analytics: 

# Location info. (shown in footer)
location: >
  School of Mathematics and Statistics<br/>
  Guangdong Univerisity of Technology<br/>
  No. 161 Yinglong Road, Tianhe District, Guangzhou<br/>
  China<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: <a href="mailto:ykuang@gdut.edu.cn" target="_blank">ykuang@gdut.edu.cn</a><br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  # - name: software
  # - name: team
  # - name: education
  # - name: volunteering

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
